// Generated by gencpp from file combi_darknet_openface2/ActionUnit.msg
// DO NOT EDIT!


#ifndef COMBI_DARKNET_OPENFACE2_MESSAGE_ACTIONUNIT_H
#define COMBI_DARKNET_OPENFACE2_MESSAGE_ACTIONUNIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace combi_darknet_openface2
{
template <class ContainerAllocator>
struct ActionUnit_
{
  typedef ActionUnit_<ContainerAllocator> Type;

  ActionUnit_()
    : name()
    , presence(0.0)
    , intensity(0.0)  {
    }
  ActionUnit_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , presence(0.0)
    , intensity(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _presence_type;
  _presence_type presence;

   typedef double _intensity_type;
  _intensity_type intensity;




  typedef boost::shared_ptr< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> const> ConstPtr;

}; // struct ActionUnit_

typedef ::combi_darknet_openface2::ActionUnit_<std::allocator<void> > ActionUnit;

typedef boost::shared_ptr< ::combi_darknet_openface2::ActionUnit > ActionUnitPtr;
typedef boost::shared_ptr< ::combi_darknet_openface2::ActionUnit const> ActionUnitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace combi_darknet_openface2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'combi_darknet_openface2': ['/root/catkin_ws/src/combi_darknet_openface2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa8dca63187d7a12cf7a6c27efaaaa8d";
  }

  static const char* value(const ::combi_darknet_openface2::ActionUnit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa8dca63187d7a12ULL;
  static const uint64_t static_value2 = 0xcf7a6c27efaaaa8dULL;
};

template<class ContainerAllocator>
struct DataType< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "combi_darknet_openface2/ActionUnit";
  }

  static const char* value(const ::combi_darknet_openface2::ActionUnit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float64 presence\n\
float64 intensity\n\
";
  }

  static const char* value(const ::combi_darknet_openface2::ActionUnit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.presence);
      stream.next(m.intensity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionUnit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::combi_darknet_openface2::ActionUnit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::combi_darknet_openface2::ActionUnit_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "presence: ";
    Printer<double>::stream(s, indent + "  ", v.presence);
    s << indent << "intensity: ";
    Printer<double>::stream(s, indent + "  ", v.intensity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMBI_DARKNET_OPENFACE2_MESSAGE_ACTIONUNIT_H
