# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from combi_darknet_openface2/Face.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Face(genpy.Message):
  _md5sum = "1621eee7fe600ba4c208a6533f5a249f"
  _type = "combi_darknet_openface2/Face"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

geometry_msgs/Vector3 left_gaze
geometry_msgs/Vector3 right_gaze

geometry_msgs/Pose head_pose

geometry_msgs/Point[] landmarks_3d
geometry_msgs/Point[] landmarks_2d

#openface_ros/ActionUnit[] action_units

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','left_gaze','right_gaze','head_pose','landmarks_3d','landmarks_2d']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Point[]','geometry_msgs/Point[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left_gaze,right_gaze,head_pose,landmarks_3d,landmarks_2d

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Face, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_gaze is None:
        self.left_gaze = geometry_msgs.msg.Vector3()
      if self.right_gaze is None:
        self.right_gaze = geometry_msgs.msg.Vector3()
      if self.head_pose is None:
        self.head_pose = geometry_msgs.msg.Pose()
      if self.landmarks_3d is None:
        self.landmarks_3d = []
      if self.landmarks_2d is None:
        self.landmarks_2d = []
    else:
      self.header = std_msgs.msg.Header()
      self.left_gaze = geometry_msgs.msg.Vector3()
      self.right_gaze = geometry_msgs.msg.Vector3()
      self.head_pose = geometry_msgs.msg.Pose()
      self.landmarks_3d = []
      self.landmarks_2d = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_13d().pack(_x.left_gaze.x, _x.left_gaze.y, _x.left_gaze.z, _x.right_gaze.x, _x.right_gaze.y, _x.right_gaze.z, _x.head_pose.position.x, _x.head_pose.position.y, _x.head_pose.position.z, _x.head_pose.orientation.x, _x.head_pose.orientation.y, _x.head_pose.orientation.z, _x.head_pose.orientation.w))
      length = len(self.landmarks_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks_2d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_2d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_gaze is None:
        self.left_gaze = geometry_msgs.msg.Vector3()
      if self.right_gaze is None:
        self.right_gaze = geometry_msgs.msg.Vector3()
      if self.head_pose is None:
        self.head_pose = geometry_msgs.msg.Pose()
      if self.landmarks_3d is None:
        self.landmarks_3d = None
      if self.landmarks_2d is None:
        self.landmarks_2d = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.left_gaze.x, _x.left_gaze.y, _x.left_gaze.z, _x.right_gaze.x, _x.right_gaze.y, _x.right_gaze.z, _x.head_pose.position.x, _x.head_pose.position.y, _x.head_pose.position.z, _x.head_pose.orientation.x, _x.head_pose.orientation.y, _x.head_pose.orientation.z, _x.head_pose.orientation.w,) = _get_struct_13d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.landmarks_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_2d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.landmarks_2d.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_13d().pack(_x.left_gaze.x, _x.left_gaze.y, _x.left_gaze.z, _x.right_gaze.x, _x.right_gaze.y, _x.right_gaze.z, _x.head_pose.position.x, _x.head_pose.position.y, _x.head_pose.position.z, _x.head_pose.orientation.x, _x.head_pose.orientation.y, _x.head_pose.orientation.z, _x.head_pose.orientation.w))
      length = len(self.landmarks_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks_2d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_2d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_gaze is None:
        self.left_gaze = geometry_msgs.msg.Vector3()
      if self.right_gaze is None:
        self.right_gaze = geometry_msgs.msg.Vector3()
      if self.head_pose is None:
        self.head_pose = geometry_msgs.msg.Pose()
      if self.landmarks_3d is None:
        self.landmarks_3d = None
      if self.landmarks_2d is None:
        self.landmarks_2d = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.left_gaze.x, _x.left_gaze.y, _x.left_gaze.z, _x.right_gaze.x, _x.right_gaze.y, _x.right_gaze.z, _x.head_pose.position.x, _x.head_pose.position.y, _x.head_pose.position.z, _x.head_pose.orientation.x, _x.head_pose.orientation.y, _x.head_pose.orientation.z, _x.head_pose.orientation.w,) = _get_struct_13d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.landmarks_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_2d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.landmarks_2d.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
